/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as ShortCodeRouteImport } from './routes/$shortCode'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppUrlShortenerRouteImport } from './routes/app/url-shortener'
import { Route as AppFileDropRouteImport } from './routes/app/file-drop'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/app.lazy').then((d) => d.Route))
const ShortCodeRoute = ShortCodeRouteImport.update({
  id: '/$shortCode',
  path: '/$shortCode',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUrlShortenerRoute = AppUrlShortenerRouteImport.update({
  id: '/url-shortener',
  path: '/url-shortener',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/app/url-shortener.lazy').then((d) => d.Route),
)
const AppFileDropRoute = AppFileDropRouteImport.update({
  id: '/file-drop',
  path: '/file-drop',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/app/file-drop.lazy').then((d) => d.Route))
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/app/dashboard.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$shortCode': typeof ShortCodeRoute
  '/app': typeof AppRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/file-drop': typeof AppFileDropRoute
  '/app/url-shortener': typeof AppUrlShortenerRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$shortCode': typeof ShortCodeRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/file-drop': typeof AppFileDropRoute
  '/app/url-shortener': typeof AppUrlShortenerRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$shortCode': typeof ShortCodeRoute
  '/app': typeof AppRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/file-drop': typeof AppFileDropRoute
  '/app/url-shortener': typeof AppUrlShortenerRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$shortCode'
    | '/app'
    | '/app/dashboard'
    | '/app/file-drop'
    | '/app/url-shortener'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$shortCode'
    | '/app/dashboard'
    | '/app/file-drop'
    | '/app/url-shortener'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/$shortCode'
    | '/app'
    | '/app/dashboard'
    | '/app/file-drop'
    | '/app/url-shortener'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShortCodeRoute: typeof ShortCodeRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$shortCode': {
      id: '/$shortCode'
      path: '/$shortCode'
      fullPath: '/$shortCode'
      preLoaderRoute: typeof ShortCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/url-shortener': {
      id: '/app/url-shortener'
      path: '/url-shortener'
      fullPath: '/app/url-shortener'
      preLoaderRoute: typeof AppUrlShortenerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/file-drop': {
      id: '/app/file-drop'
      path: '/file-drop'
      fullPath: '/app/file-drop'
      preLoaderRoute: typeof AppFileDropRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppFileDropRoute: typeof AppFileDropRoute
  AppUrlShortenerRoute: typeof AppUrlShortenerRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppFileDropRoute: AppFileDropRoute,
  AppUrlShortenerRoute: AppUrlShortenerRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShortCodeRoute: ShortCodeRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
