# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core project to Azure Function App - ar-go

on:
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './ArGo.Api' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '9.0' # set this to the dotnet version to use

jobs:
  build:
    runs-on: ubuntu-latest
    environment: AZURE

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Build ArGo.Web UI
        run: |
          pushd './ArGo.Web'
          npm install
          npm run build
          popd

      - name: Substitute JSON (migrated from ar-auth)
        uses: restackio/update-json-file-action@2.1
        with:
          file:  ArGo.Web/dist/config.json
          fields: '{"api":"${{ vars.API }}", "redirectUri":"${{ vars.REDIRECT_URI }}", "authUri":"${{ vars.AUTH_API }}", "clientId":"${{ vars.CLIENT_ID }}", "scope":"${{ vars.SCOPE }}"}'

      - name: Move/Rename config.json to js
        run: |
              echo window.webConfig= > config.js
              cat config.json >> config.js
        working-directory: ArGo.Web/dist

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet publish --configuration Release --output ./output
          popd

      - name: Copy UI to Function App wwwroot
        run: |
          mkdir -p ./${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output/wwwroot
          cp -r ./ArGo.Web/dist/* ./${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output/wwwroot/

      - name: 'Zip artifact for deployment'
        run: |
          pushd ./${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output
          zip -r ../../release.zip .
          popd

      - name: 'Upload Build Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: function-app-package
          path: release.zip
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: 'Download Build Artifact'
        uses: actions/download-artifact@v4
        with:
          name: function-app-package

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7FE297767A8642F0A7750B510C06B1A0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D1D4848B941D4FB89D85872DC1EFA9CC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9003638F840F4730814638CC806F27A1 }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'ar-go'
          slot-name: 'Production'
          package: ./release.zip
          
